# Config file for Telegram Captcha Bot

# Delete all joins and removals (applicable only for del strategy)
silent_mode = false

# Captcha button timeout
restrict_seconds = 30

# Ban duration (set 0 to ban forever)
ban_seconds = 0

# Button text
button_text = "I'm not a robot!"

# Bot sends this message to new users
welcome_message = "Hello! This is spam protection system. Please press the button in 30 seconds or you will be banned!"

# Edit welcome message with this text if user passed validation
after_success_message = "User passed the validation."

# Edit welcome message with this text if user failed validation
after_fail_message = "User didn't pass the validation and banned."

# Show success and failure messages or delete them. Pick "show" or "del"
print_success_and_fail_messages_strategy = "show"

# Respond message for passed user
passed_respond = "Validation passed!"

# Respond message for other users
others_respond = "This button isn't for you"
